version: '3.8'

services:
  biarbala:
    build: .
    ports:
      - "8080:8080"  # gRPC
      - "8081:8081"  # HTTP
      - "9090:9090"  # Metrics
    environment:
      - DATABASE_MONGODB_URI=mongodb://mongodb:27017
      - CACHE_REDIS_ADDR=redis:6379
    volumes:
      - ./uploads:/app/uploads
      - ./served:/app/served
      - ./temp:/app/temp
    depends_on:
      - mongodb
      - redis
    networks:
      - biarbala-network

  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=biarbala
    networks:
      - biarbala-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - biarbala-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - biarbala
    networks:
      - biarbala-network

volumes:
  mongodb_data:
  redis_data:

networks:
  biarbala-network:
    driver: bridge
