server:
  grpc:
    port: 8080
    host: "0.0.0.0"
    enable_reflection: true
    enable_web_grpc: true
  http:
    port: 8081
    host: "0.0.0.0"
  static:
    upload_dir: "./uploads"
    serve_dir: "./served"

database:
  mongodb:
    uri: "mongodb://localhost:27017"
    database: "biarbala"
    timeout: 30s
  postgresql:
    host: "localhost"
    port: 5432
    database: "keycloak"
    username: "keycloak"
    password: "keycloak"
    ssl_mode: "disable"

storage:
  minio:
    endpoint: "localhost:9000"
    access_key: "minioadmin"
    secret_key: "minioadmin"
    use_ssl: false
    bucket_name: "biarbala"

cache:
  redis:
    addr: "localhost:6379"
    password: ""
    db: 0
    timeout: 30s

logging:
  level: "info"
  format: "text"
  output: "stdout"

metrics:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"

upload:
  max_file_size: 100MB
  allowed_formats: ["tar", "gz", "zip"]
  temp_dir: "./temp"

security:
  rate_limit:
    enabled: true
    requests_per_minute: 60

auth:
  keycloak:
    enabled: true
    server_url: "http://localhost:8082"
    realm: "biarbala"
    client_id: "biarbala-client"
    client_secret: "biarbala-secret"
    admin_username: "admin"
    admin_password: "admin123"
    redirect_url: "http://localhost:8081/auth/callback"
    logout_url: "http://localhost:8081/auth/logout"
    database: "dev-file"  # Options: dev-file, dev-mem, postgres
    db_url: "jdbc:postgresql://localhost:5432/keycloak"
  jwt:
    secret_key: "biarbala-jwt-secret-key-change-in-production"
    expiration: "24h"
    refresh_expiration: "168h"
  # GitHub and Google OAuth are now configured in Keycloak as identity providers

email:
  enabled: false
  smtp_host: "localhost"
  smtp_port: 587
  smtp_username: ""
  smtp_password: ""
  use_tls: true
  from_email: "noreply@biarbala.ir"
  from_name: "Biarbala"
  base_url: "http://localhost:8081"

domain:
  main_domain: "biarbala.ir"
  subdomain_min_length: 6
  verification_timeout: "24h"
  ssl:
    provider: "letsencrypt"
    auto_renew: true
    renew_threshold: "30d"
